# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02bd357e51df7a9f71cef0b7b1538e8f2a0da0fa969480cfbf9a5a2ae75c69c802c6cd10a2ba8804d179b3203ad22e0d14fb9f3d2cba1224755e216d61e5fd7d

test:
  secret_key_base: 4acd4006af3309443e9493819156b62f017595f5ce3a5dab66a0e651bb41a3daf80628a6a963f2f89e8385d974f2ae8c224bb3ec0674b0d88c1a16fef7f32c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4ae315e715209d2ae84ef5a8ff3c02332783e4231673562aa8a3ef9802f700fa2c1002c61132ecc7d5d174b817570cb416eaa74af9ca484e1e8343550f5779bb
